
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crm
      MYSQL_PASSWORD: crm
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      COOKIE_SAMESITE: Lax
      SESSION_COOKIE_NAME: PHPSESSID
    depends_on:
      - mysql

  nuxt:
    build: 
      context: ./front-end
    ports:
      - "3000:3000"
    environment:
      - NUXT_API_URL=http://nest:3001
    depends_on:
      - nest

  nest:
    build: 
      context: ./back-end
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=crm
      - DATABASE_PASSWORD=crm
      - DATABASE_NAME=crm
    depends_on:
      - mysql

volumes:
  mysql-data:
